import type { Metadata } from "next";
import "../styles/tailwind.css"
import "../styles/app.css"

export const metadata: Metadata = {
  title: "Web Forms",
  authors: [{ name: "mdmahikaishar", url: "mahikaishar@gmail.com" }],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        {children}
      </body>
    </html>
  );
}
